# Generated by Django 4.1.5 on 2023-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_document_document_alter_document_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='filename',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(default='pending', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
